### ISSUE TITLE
resolv against specific nameserver addresses

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly.rs#13]
Right now, `resolv` takes a query/string and resolves it against 8.8.8.8. It should let you specify a nameserver to use for resolution.

It's a little `fetch`-like, so the most consistent way to do this might be to have a signature like:

```typescript
interface DNSRequestInit{
  nameserver: string
}

resolv(name: string | DNSRequest, init?: DNSRequestInit)
```

**Comment by jeromegn** [comment]
Fixed in 4dd220d

```typescript
export interface DNSRequestInit {
  type?: fbs.DnsRecordType // DNSRecordType.A, DNSRecordType.AAAA, ...
  nameservers?: string[] // ["ns1.example.com", "ns2.example.com", ...]
}
```

For now, it'll only pick the first one. No retry mechanism either.
