### ISSUE TITLE
Handle Let's Encrypt http acme challenges

### ISSUE THREAD

**Issue by jeromegn** [superfly/fly.rs#23]
- Respond to `/.well-known/acme-challenge/[hash]`
- Store the content to respond with somewhere (fs, redis, etc.), abstracted as a trait
- Pass the store as an option to the http server

**Comment by michaeldwan** [comment]
@mrkurt I also think this could be done in JS, perhaps intercepting `/.well-known/acme-challenge/*` inside the event listener before dispatching to app's fetch handler. Is that what you meant by having apps do it themselves, or were you suggesting users write code (or register a handler from v8env) for this?
